version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:latest
    container_name: mysql-database
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: productdb
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - springboot-network

  # Spring Boot Application
  app:
    build: .
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/productdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user_password
    depends_on:
      - mysql
    networks:
      - springboot-network

networks:
  springboot-network:

volumes:
  mysql-data: